package com.catbreedapp.catbreedsapp.model


data class Breed(
    val weight: Weight,
    val id: String,
    val name: String,
    val cfa_url: String? = null,
    val vetstreet_url: String? = null,
    val vcahospitals_url: String? = null,
    val temperament: String,
    val origin: String,
    val country_codes: String,
    val country_code: String,
    val description: String,
    val life_span: String,
    val indoor: Long,
    val lap: Long? = null,
    val alt_names: String? = null,
    val adaptability: Long,
    val affection_level: Long,
    val child_friendly: Long,
    val dog_friendly: Long,
    val energy_level: Long,
    val grooming: Long,
    val health_issues: Long,
    val intelligence: Long,
    val shedding_level: Long,
    val social_needs: Long,
    val stranger_friendly: Long,
    val vocalisation: Long,
    val experimental: Long,
    val hairless: Long,
    val natural: Long,
    val rare: Long,
    val rex: Long,
    val suppressed_tail: Long,
    val short_legs: Long,
    val wikipedia_url: String? = null,
    val hypoallergenic: Long,
    val reference_image_id: String? = null,
    val image: Image? = null,
    val cat_friendly: Long? = null,
    val bidability: Long? = null
)
